import Foundation

/// Code for the code index: a source file, a repo's doc or a notebook, cut into stretches of whole lines (a notebook's
/// into whole cells) that the model reads one at a time, each knowing where it is, so that a result opens there.
public enum CodeExtractor {
    /// A stretch of a file: its text, and its first and last lines (or cells), from 1.
    struct Piece: Sendable, Equatable {
        let text: String
        let first: Int
        let last: Int
    }

    struct File: Sendable {
        let pieces: [Piece]
        /// For the model, the file's title: its path in its repo ("payments/retry.py" in the "billing" repo reads
        /// "billing/payments/retry.py"), which says more about code than its name alone (2026-10-09, the real-code
        /// eval: the file name alone had 22 vs 24 of 27 in the top 5, MRR 0.69 vs 0.79).
        let title: String
        /// The repo (or code project) it's in, if any.
        let repo: String?
        let lines: Int
        /// A notebook's cells (code and notes; outputs are never read). Nil for anything else.
        let cells: Int?
    }

    /// The model reads 2,048 tokens of an input at most; a single line longer than this is cut here.
    static let longestPiece = 4000

    static func read(_ url: URL, options: IndexOptions) throws -> File {
        let data = try Data(contentsOf: url)
        let (repo, title) = place(of: url.path)
        if url.pathExtension.lowercased() == "ipynb" {
            let cells = try notebookCells(data)
            let text = cells.joined(separator: "\n")
            // As for any code: more than this was written by a program (data pasted into a cell).
            if text.utf8.count > options.maxCodeBytes { throw ExtractError.leftOut("cells over \(options.maxCodeBytes >> 20) MB") }
            try check(text, source: true)
            return File(pieces: Self.cells(cells, size: options.codeStretch), title: title, repo: repo,
                        lines: lineCount(text), cells: cells.count)
        }
        if data.prefix(8000).contains(0) { throw ExtractError.leftOut("not text") }
        let text = String(data: data, encoding: .utf8) ?? String(data: data, encoding: .isoLatin1) ?? ""
        try check(text, source: Rules.sourceExtensions.contains(url.pathExtension.lowercased()))
        return File(pieces: lines(text, size: options.codeStretch), title: title, repo: repo, lines: lineCount(text),
                    cells: nil)
    }

    /// Code that's no use to read: it holds a private key, or (`source`: code, not a repo's notes) a program wrote it
    /// (its generator says so at the top: "DO NOT EDIT", "@generated") or it's minified.
    static func check(_ text: String, source: Bool) throws {
        if text.contains("PRIVATE KEY-----") { throw ExtractError.leftOut("holds a private key") }
        guard source else { return }
        let top = text.prefix(1000)
        for mark in ["DO NOT EDIT", "@generated", "Code generated by", "Autogenerated by", "Generated by the protocol"]
        where top.contains(mark) {
            throw ExtractError.leftOut("made by a program (“\(mark)”)")
        }
        // Minified: few lines, and long ones (a bundle can be one line of 100,000 characters).
        let lines = max(1, lineCount(text)), characters = text.count
        if characters / lines > 300, text.split(separator: "\n").contains(where: { $0.count > 3000 }) {
            throw ExtractError.leftOut("minified (\(characters / lines) characters a line)")
        }
    }

    static func lineCount(_ text: String) -> Int {
        var count = 0
        for byte in text.utf8 where byte == 0x0A { count += 1 }
        return text.hasSuffix("\n") || text.isEmpty ? count : count + 1
    }

    // MARK: Stretches of lines

    /// Stretches of whole lines, each at most `size` characters (a longer line is a stretch of its own). A stretch ends,
    /// when it can, where the code does: before a line that starts a new block at the left margin, or after a blank
    /// line, in its last 60%. One that had to stop in the middle of a block hands its last two lines on to the next,
    /// so whatever spans the cut is read whole once.
    static func lines(_ text: String, size: Int = 1800) -> [Piece] {
        // Swift reads "\r\n" as one character: both end a line, as they do in an editor.
        var lines = text.split(omittingEmptySubsequences: false, whereSeparator: { $0 == "\n" || $0 == "\r\n" })
        if lines.last?.isEmpty == true { lines.removeLast() }   // the final newline
        let count = lines.count
        var offsets = [0]   // characters before each line (each with its newline)
        offsets.reserveCapacity(count + 1)
        for line in lines { offsets.append(offsets.last! + line.count + 1) }
        func blank(_ index: Int) -> Bool { lines[index].allSatisfy(\.isWhitespace) }
        func startsBlock(_ index: Int) -> Bool {
            guard let first = lines[index].first, !first.isWhitespace else { return false }
            // A closing line belongs to the block above it.
            let trimmed = lines[index].trimmingCharacters(in: .whitespaces)
            return !"})]".contains(first) && !closers.contains(trimmed)
        }

        var pieces: [Piece] = []
        var start = 0
        while start < count {
            while start < count, blank(start) { start += 1 }
            guard start < count else { break }
            var end = start + 1   // the stretch is lines[start..<end]
            while end < count, offsets[end + 1] - offsets[start] <= size { end += 1 }
            var natural = end >= count
            if !natural {
                // Where the code breaks by itself, keeping at least 40% of a stretch: a new block after a blank line
                // first, then any blank line or new block.
                let floor = offsets[start] + size * 2 / 5
                func lastBreak(_ isBreak: (Int) -> Bool) -> Int? {
                    var line = end
                    while line > start + 1, offsets[line] >= floor {
                        if isBreak(line) { return line }
                        line -= 1
                    }
                    return nil
                }
                if let cut = lastBreak({ startsBlock($0) && blank($0 - 1) }) ?? lastBreak({ blank($0 - 1) || startsBlock($0) }) {
                    end = cut
                    natural = true
                }
            }
            var last = end
            while last > start + 1, blank(last - 1) { last -= 1 }   // blank lines at its end don't count
            var body = lines[start..<last].joined(separator: "\n")
            if body.count > longestPiece { body = String(body.prefix(longestPiece)) }
            pieces.append(Piece(text: body, first: start + 1, last: last))
            start = natural ? end : max(end - 2, start + 1)
        }
        return pieces
    }

    /// A stretch in one line, for result lists: its first line that defines something ("def retry_with_backoff(…"),
    /// else its first line of code (not a comment, an import or a closing brace).
    static func summary(_ text: String) -> String {
        let lines = text.split(whereSeparator: { $0 == "\n" || $0 == "\r\n" })
            .map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
        let definition = lines.first { line in
            let first = line.split(whereSeparator: \.isWhitespace).prefix(4).map(String.init)
            return first.contains { CodeLookup.definesSomething($0) }
        }
        let code = lines.first { line in
            !["//", "#", "/*", "*", "--", "\"\"\"", "import ", "from ", "#include", "using ", "package ", "}", ")", "@"]
                .contains(where: line.hasPrefix)
        }
        let line = definition ?? code ?? lines.first ?? ""
        return line.count > 160 ? String(line.prefix(160)) + "…" : line
    }

    /// Lines that close a block (shell, Ruby, Lua, Objective-C, the C preprocessor).
    private static let closers: Set<String> = ["end", "fi", "done", "esac", "@end", "#endif", "end;", "end)"]

    // MARK: Notebooks

    /// The cells of a Jupyter notebook, code and notes alike, as their text. Outputs (pictures, tables, logs) aren't
    /// read: they're results, not what anyone wrote.
    static func notebookCells(_ data: Data) throws -> [String] {
        guard let notebook = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw ExtractError.unreadable("not a notebook")
        }
        // nbformat 4 keeps its cells at the top; nbformat 3 inside worksheets, with code in "input".
        let cells = notebook["cells"] as? [[String: Any]]
            ?? (notebook["worksheets"] as? [[String: Any]])?.first?["cells"] as? [[String: Any]] ?? []
        return cells.map { cell in
            let source = cell["source"] ?? cell["input"]
            return (source as? [String])?.joined() ?? source as? String ?? ""
        }
    }

    /// Whole cells to a stretch, up to `size` characters; a longer cell is cut into stretches of lines that all point
    /// at it. Empty cells are passed over.
    static func cells(_ cells: [String], size: Int = 1800) -> [Piece] {
        var pieces: [Piece] = []
        var text = "", first = 0, last = 0
        func flush() {
            guard !text.isEmpty else { return }
            pieces.append(Piece(text: text, first: first, last: last))
            text = ""
        }
        for (index, cell) in cells.enumerated() {
            let body = cell.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !body.isEmpty else { continue }
            let number = index + 1
            if body.count > size {
                flush()
                pieces += lines(body, size: size).map { Piece(text: $0.text, first: number, last: number) }
                continue
            }
            if !text.isEmpty, text.count + 2 + body.count > size { flush() }
            if text.isEmpty {
                first = number
                text = body
            } else {
                text += "\n\n" + body
            }
            last = number
        }
        flush()
        return pieces
    }

    // MARK: Where it is

    /// The repo (or code project) `path` is in, and the file's title: its path from the repo's folder, the repo's name
    /// first. Outside any: its folder's name and its own.
    static func place(of path: String) -> (repo: String?, title: String) {
        let home = FileManager.default.homeDirectoryForCurrentUser.path
        var folder = (path as NSString).deletingLastPathComponent
        var repo: String?
        while folder.count > 1, folder != home {
            if FileManager.default.fileExists(atPath: folder + "/.git") || Rules.isProjectRoot(folder) {
                repo = folder
                break
            }
            folder = (folder as NSString).deletingLastPathComponent
        }
        if let repo {
            let parent = (repo as NSString).deletingLastPathComponent
            return (repo, String(path.dropFirst(parent.count + 1)))
        }
        let components = (path as NSString).pathComponents
        return (nil, components.suffix(2).joined(separator: "/"))
    }

    /// "Swift", "Python", "Markdown": what a file's extension says it's written in.
    public static func language(of path: String) -> String {
        let name = (path as NSString).lastPathComponent
        let ext = (name as NSString).pathExtension.lowercased()
        if let language = languages[ext] { return language }
        if Rules.codeFileNames.contains(name) || name.hasPrefix("Dockerfile") { return name }
        return ext.isEmpty ? "Text" : ext.uppercased()
    }

    private static let languages: [String: String] = [
        "py": "Python", "pyi": "Python", "pyx": "Cython", "ipynb": "Notebook", "c": "C", "h": "C header",
        "cc": "C++", "cpp": "C++", "cxx": "C++", "hpp": "C++ header", "hh": "C++ header", "hxx": "C++ header",
        "m": "Objective-C", "mm": "Objective-C++", "swift": "Swift", "ts": "TypeScript", "tsx": "TypeScript",
        "mts": "TypeScript", "cts": "TypeScript", "js": "JavaScript", "jsx": "JavaScript", "mjs": "JavaScript",
        "cjs": "JavaScript", "go": "Go", "rs": "Rust", "java": "Java", "kt": "Kotlin", "kts": "Kotlin",
        "scala": "Scala", "groovy": "Groovy", "rb": "Ruby", "php": "PHP", "cs": "C#", "fs": "F#", "sh": "Shell",
        "bash": "Shell", "zsh": "Shell", "fish": "Shell", "ps1": "PowerShell", "lua": "Lua", "pl": "Perl",
        "pm": "Perl", "r": "R", "jl": "Julia", "dart": "Dart", "sql": "SQL", "vue": "Vue", "svelte": "Svelte",
        "astro": "Astro", "html": "HTML", "htm": "HTML", "css": "CSS", "scss": "SCSS", "sass": "Sass",
        "less": "Less", "gradle": "Gradle", "cmake": "CMake", "mk": "Makefile", "proto": "Protocol Buffers",
        "graphql": "GraphQL", "gql": "GraphQL", "tf": "Terraform", "hcl": "HCL", "nix": "Nix", "zig": "Zig",
        "hs": "Haskell", "ex": "Elixir", "exs": "Elixir", "erl": "Erlang", "clj": "Clojure", "cljs": "ClojureScript",
        "elm": "Elm", "ml": "OCaml", "mli": "OCaml", "vim": "Vim script", "el": "Emacs Lisp", "lisp": "Lisp",
        "asm": "Assembly", "s": "Assembly", "metal": "Metal", "glsl": "GLSL", "hlsl": "HLSL", "wgsl": "WGSL",
        "cu": "CUDA", "cuh": "CUDA", "ino": "Arduino", "v": "Verilog", "sv": "SystemVerilog", "tex": "LaTeX",
        "md": "Markdown", "markdown": "Markdown", "rst": "reStructuredText", "adoc": "AsciiDoc", "org": "Org",
        "txt": "Text", "yaml": "YAML", "yml": "YAML", "toml": "TOML",
    ]
}

/// Names in code: a query that's a name finds it exactly, and the place that defines it rather than every place
/// that uses it; a result opens at the line that matched.
public enum CodeLookup {
    /// The words keyword search keeps a name from code as ("quantize_row_q8_0_ref" → quantize row q8 0 ref, as one
    /// phrase), when the query is one: snake_case, camelCase, dotted, or with digits. Nil for words anyone would say
    /// ("retry", "Renamer"), which are searched as words and by meaning.
    public static func identifier(_ query: String) -> [String]? {
        var name = query.trimmingCharacters(in: .whitespacesAndNewlines)
        if name.hasSuffix("()") { name.removeLast(2) }
        guard name.range(of: #"^[A-Za-z_$][A-Za-z0-9_$]*(?:(?:\.|::|->|#)[A-Za-z_$][A-Za-z0-9_$]*)*$"#,
                         options: .regularExpression) != nil else { return nil }
        let camel = name.dropFirst().contains(where: \.isUppercase) && name.contains(where: \.isLowercase)
        guard camel || name.contains(where: { "_.:#$".contains($0) || $0.isNumber }) else { return nil }
        return name.lowercased().components(separatedBy: CharacterSet.alphanumerics.inverted).filter { !$0.isEmpty }
    }

    /// The keyword search pattern for an identifier's words: one phrase, so they match only side by side, as written.
    static func phrase(_ words: [String]) -> String {
        "\"" + words.joined(separator: " ") + "\""
    }

    /// Where `name` is defined in `text` (a stretch whose first line is `first`): the line, and how surely. 2 after a
    /// word that defines something (def, func, class, function, struct, #define, @implementation…) or as a C-style
    /// definition (a type before it, its parameters after it, no "=" or call around it); 1 for a declaration (the
    /// same, ending in ";"). Nil when the stretch only uses it.
    static func definition(of name: String, in text: String, first: Int) -> (line: Int, strength: Int)? {
        var best: (line: Int, strength: Int)?
        for (offset, line) in lines(text).enumerated() {
            for range in occurrences(of: name, in: line) {
                let before = line[..<range.lowerBound].trimmingCharacters(in: .whitespaces)
                let after = line[range.upperBound...].trimmingCharacters(in: .whitespaces)
                let strength = definitionStrength(before: before, after: after, line: String(line))
                if strength > (best?.strength ?? 0) { best = (first + offset, strength) }
                if strength == 2 { return best }
            }
        }
        return best
    }

    /// A word that starts a definition ("def", "func", "class", "@implementation"…).
    static func definesSomething(_ word: String) -> Bool { definers.contains(word) && word != "let" && word != "var"
        && word != "const" && word != "val" }

    private static let definers: Set<String> = [
        "def", "func", "fn", "fun", "function", "class", "struct", "enum", "protocol", "interface", "trait", "type",
        "typealias", "actor", "extension", "impl", "module", "namespace", "object", "record", "macro", "const", "let",
        "var", "val", "union", "mod", "sub", "@interface", "@implementation", "@protocol", "#define", "function*",
    ]
    /// Words before a name that mean it's being used, not defined ("await name(…)", "return name(…)").
    private static let users: Set<String> = [
        "return", "await", "yield", "throw", "new", "else", "case", "print", "echo", "assert", "not", "and", "or", "in",
        "is", "do", "go", "defer", "try", "catch", "if", "while", "for", "typeof", "delete", "raise", "import", "from",
    ]

    private static func definitionStrength(before: String, after: String, line: String) -> Int {
        let previous = before.split(whereSeparator: \.isWhitespace).last.map(String.init) ?? ""
        if definers.contains(previous) { return 2 }
        if before.hasPrefix("func ("), before.hasSuffix(")") { return 2 }                     // a Go method
        if before.hasPrefix("- (") || before.hasPrefix("+ (") { return after.hasPrefix(":") || after.isEmpty
            || after.hasPrefix("{") || after.hasPrefix(";") ? 2 : 0 }                          // an Objective-C method
        // C-style: "static void name(…) {", "struct gguf_context * name(…)", not a call or an assignment.
        guard after.hasPrefix("("), !before.isEmpty, !users.contains(previous),
              !before.contains(where: { "=(,.!?".contains($0) }), !before.contains("->"),
              let last = before.last, last.isLetter || last.isNumber || "*&>_]".contains(last) else { return 0 }
        return line.trimmingCharacters(in: .whitespaces).hasSuffix(";") ? 1 : 2
    }

    /// The line (from `first`) to open at for `words`: the first line with one of them that defines something ("def
    /// retry_with_backoff"), else the first such line of code (not a comment), else the first such line. A word counts
    /// as itself or as a part of a name (the "retry" of retryWithBackoff and retry_with_backoff). Nil when none is there.
    static func firstLine(with words: [String], in text: String, first: Int) -> Int? {
        let words = words.filter { $0.count >= 2 }.map { $0.lowercased() }
        guard !words.isEmpty else { return nil }
        var firstCode: Int?, firstAny: Int?
        for (offset, line) in lines(text).enumerated() where words.contains(where: { has($0, line) }) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.split(whereSeparator: \.isWhitespace).prefix(4).contains(where: { definesSomething(String($0)) }) {
                return first + offset
            }
            if firstCode == nil, !commentStarts.contains(where: trimmed.hasPrefix) { firstCode = offset }
            if firstAny == nil { firstAny = offset }
        }
        return (firstCode ?? firstAny).map { first + $0 }
    }

    /// How comments and docstrings start.
    private static let commentStarts = ["//", "#", "/*", "*", "--", "\"\"\"", "'''", "<!--", ";"]

    /// Whether `line` has `word` (lowercased) as a word or as the start of a name's part.
    private static func has(_ word: String, _ line: Substring) -> Bool {
        let lower = line.lowercased()
        var searchStart = lower.startIndex
        while let found = lower.range(of: word, range: searchStart..<lower.endIndex) {
            // A word or a name's part starts here: at the line's start, after something that isn't a letter or a
            // digit, or at a capital letter (camelCase).
            let start = line.index(line.startIndex, offsetBy: lower.distance(from: lower.startIndex, to: found.lowerBound),
                                   limitedBy: line.endIndex) ?? line.endIndex
            if found.lowerBound == lower.startIndex
                || !lower[lower.index(before: found.lowerBound)].isLetter
                    && !lower[lower.index(before: found.lowerBound)].isNumber
                || start < line.endIndex && line[start].isUppercase {
                return true
            }
            searchStart = found.upperBound
        }
        return false
    }

    private static func lines(_ text: String) -> [Substring] {
        text.split(omittingEmptySubsequences: false, whereSeparator: { $0 == "\n" || $0 == "\r\n" })
    }

    /// Where `name` is in `line` as a whole name (not a part of a longer one), whatever its case.
    private static func occurrences(of name: String, in line: Substring) -> [Range<Substring.Index>] {
        var found: [Range<Substring.Index>] = []
        var start = line.startIndex
        while let range = line.range(of: name, options: .caseInsensitive, range: start..<line.endIndex) {
            let clearBefore = range.lowerBound == line.startIndex || !isNameCharacter(line[line.index(before: range.lowerBound)])
            let clearAfter = range.upperBound == line.endIndex || !isNameCharacter(line[range.upperBound])
            if clearBefore, clearAfter { found.append(range) }
            start = range.upperBound
        }
        return found
    }

    private static func isNameCharacter(_ character: Character) -> Bool {
        character.isLetter || character.isNumber || character == "_" || character == "$"
    }
}
